spring:
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-flash
          temperature: 0.7
  data:
    redis:
      host: localhost
      port: 6379
      password: 20020315   # 如果 Redis 设了密码就打开这行
      database: 0